# Generated by Django 4.2 on 2024-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_services_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(),
        ),
    ]
