# Generated by Django 4.2 on 2024-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_services_updated_at_alter_services_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created_at']},
        ),
    ]
