# Generated by Django 4.2 on 2024-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_specialservices_alter_services_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['created_at']},
        ),
    ]
