# Generated by Django 4.2 on 2024-07-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_questions_alter_services_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contect', models.TextField()),
                ('price', models.FloatField(default=10)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('propertyes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.propertyes')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
