# Generated by Django 4.2 on 2024-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_alter_makers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makers',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
