# Generated by Django 4.2 on 2024-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_alter_makers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='makers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
