# Generated by Django 4.2 on 2024-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_makers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makers',
            name='skills',
        ),
        migrations.AddField(
            model_name='makers',
            name='skills',
            field=models.ManyToManyField(to='root.skills'),
        ),
    ]
